Update pom.xml
It fails on POST request with 
javax.servlet.ServletException: java.lang.UnsupportedOperationException: Asynchronous processing not supported on Servlet 2.x container.
jersey-container-servlet needs to be a dependency since it is servlet 3.x implementation, not jersey-container-servlet-core which is servlet 2.x implementation. See https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet-core and https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet